"use strict";
const state={csrf:"",preview:null,loaded:{today:false,portfolio:false,relationships:false}};
const $=id=>document.getElementById(id);

async function api(url,options={}){
  const headers={"Content-Type":"application/json",...(options.headers||{})};
  if(options.method&&options.method!=="GET") headers["X-CSRF-Token"]=state.csrf;
  const r=await fetch(url,{credentials:"same-origin",...options,headers});
  let body={};try{body=await r.json();}catch{}
  if(r.status===401){location.href="/painel";throw new Error("Sessão encerrada.");}
  if(!r.ok) throw new Error(body.erro||"Não foi possível concluir a ação.");
  return body;
}
function el(tag,attrs={},children=[]){const node=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==="class")node.className=v;else if(k==="text")node.textContent=v;else if(k.startsWith("data-"))node.setAttribute(k,v);else node[k]=v;}for(const child of [].concat(children)){if(child!=null)node.append(child.nodeType?child:document.createTextNode(String(child)));}return node;}
const money=v=>v==null?"Preço a confirmar":Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const date=v=>v?new Date(v).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}):"Sem prazo";
function skeletons(target,n=3){target.replaceChildren(...Array.from({length:n},()=>el("div",{class:"skeleton"})));}
function empty(target,title,copy){target.replaceChildren(el("div",{class:"empty-card"},[el("h3",{text:title}),el("p",{text:copy})]));}
function errorCard(target,error){target.replaceChildren(el("div",{class:"error-card"},[el("h3",{text:"Não foi possível carregar"}),el("p",{text:error.message})]));}
function toast(message){const t=$("toast");t.textContent=message;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,2800);}
function badge(priority){const labels={baixa:"Baixa",normal:"Normal",alta:"Atenção",critica:"Crítica"};const cls=priority==="critica"?"badge critical":priority==="alta"?"badge high":"badge";return el("span",{class:cls,text:labels[priority]||"Ação"});}

async function loadToday(force=false){if(state.loaded.today&&!force)return;const target=$("todayActions");skeletons(target);try{const data=await api("/painel/api/os/hoje");state.csrf=data.csrf||state.csrf;state.loaded.today=true;const c=data.counts||{};const cards=[[c.tasks||0,"ações pendentes"],[c.properties||0,"imóveis na carteira"],[c.contacts||0,"relacionamentos"],[c.opportunities||0,"oportunidades abertas"]];$("todayCounts").replaceChildren(...cards.map(([v,l])=>el("div",{class:"count-card"},[el("strong",{text:String(v)}),el("span",{text:l})])));$("todaySummary").textContent=data.actions?.length?`Há ${data.actions.length} item(ns) priorizado(s). O que está funcionando bem não ocupa espaço.`:"Nenhuma pendência crítica agora. Use Capturar para registrar o próximo movimento.";renderActions(data.actions||[]);}catch(e){errorCard(target,e);}}
function renderActions(actions){const target=$("todayActions");if(!actions.length)return empty(target,"Seu dia está limpo","Quando houver prazo, oportunidade ou cadastro incompleto, a próxima ação aparecerá aqui.");target.replaceChildren(...actions.map(a=>{const action=el("button",{class:"card-action",type:"button",text:a.actionLabel||"Abrir"});if(a.source==="task")action.addEventListener("click",()=>completeTask(a.id,action));else action.addEventListener("click",()=>switchView(a.entityType==="inventory_property"?"portfolio":"relationships"));return el("article",{class:"action-card"},[el("div",{class:"action-top"},[el("div",{},[el("h3",{text:a.title}),el("p",{text:a.reason})]),badge(a.priority)]),el("div",{class:"meta"},[el("span",{text:date(a.dueAt)}),el("span",{text:a.source==="property_gap"?"Cadastro progressivo":a.source==="opportunity"?"Oportunidade":"Tarefa"})]),action]);}));}
async function completeTask(id,button){button.disabled=true;button.textContent="Concluindo…";try{await api(`/painel/api/os/tarefas/${id}/concluir`,{method:"POST",body:"{}"});toast("Tarefa concluída.");state.loaded.today=false;await loadToday(true);}catch(e){toast(e.message);button.disabled=false;button.textContent="Marcar como concluída";}}

async function loadPortfolio(){if(state.loaded.portfolio)return;const target=$("portfolioList");skeletons(target);try{const data=await api("/painel/api/os/carteira");state.loaded.portfolio=true;const rows=data.properties||[];if(!rows.length)return empty(target,"Sua carteira ainda está vazia","Capture o primeiro imóvel por texto. Ele nascerá como prospecção e ganhará detalhes progressivamente.");target.replaceChildren(...rows.map(p=>el("article",{class:"entity-card"},[el("div",{class:"entity-top"},[el("div",{},[el("h3",{text:p.title||"Imóvel"}),el("p",{text:[p.neighborhood,p.owner_name?`Proprietário: ${p.owner_name}`:"Proprietário a vincular"].filter(Boolean).join(" · ")})]),el("span",{class:"badge",text:stageLabel(p.capture_stage)})]),el("div",{class:"meta"},[el("span",{text:money(p.asking_price)}),el("span",{text:`${p.pending_tasks||0} pendência(s)`}),el("span",{text:`${p.open_opportunities||0} oportunidade(s)`})])])));}catch(e){errorCard(target,e);}}
const stageLabel=s=>({prospect:"Prospecção",visited:"Visitado",captured:"Captado",ready_to_publish:"Pronto para divulgar",qualified:"Qualificado",inactive:"Inativo",sold:"Vendido",rented:"Alugado"})[s]||s;

async function loadRelationships(){if(state.loaded.relationships)return;const target=$("relationshipsList");skeletons(target);try{const data=await api("/painel/api/os/relacionamentos");state.loaded.relationships=true;const rows=data.contacts||[];if(!rows.length)return empty(target,"Nenhum relacionamento registrado","Proprietários e clientes aparecerão aqui quando forem capturados ou vinculados a uma oportunidade.");target.replaceChildren(...rows.map(c=>el("article",{class:"entity-card"},[el("div",{class:"entity-top"},[el("div",{},[el("h3",{text:c.name}),el("p",{text:[typeLabel(c.type),c.phone?`Telefone final ${String(c.phone).slice(-4)}`:null].filter(Boolean).join(" · ")})]),el("span",{class:"badge",text:`${c.open_opportunities||0} aberta(s)`})]),el("div",{class:"meta"},[el("span",{text:c.last_interaction_at?`Última interação: ${date(c.last_interaction_at)}`:"Sem interação registrada"}),el("span",{text:c.source||"cadastro"})])])));}catch(e){errorCard(target,e);}}
const typeLabel=t=>({proprietario:"Proprietário",comprador:"Comprador",locatario:"Locatário",investidor:"Investidor",parceiro:"Parceiro",incorporador:"Incorporador",fornecedor:"Fornecedor"})[t]||t;

function switchView(name){document.querySelectorAll(".view").forEach(v=>{const active=v.dataset.view===name;v.hidden=!active;v.classList.toggle("is-active",active);});document.querySelectorAll(".nav-item[data-target]").forEach(b=>{const active=b.dataset.target===name;b.classList.toggle("is-active",active);if(active)b.setAttribute("aria-current","page");else b.removeAttribute("aria-current");});if(name==="today")loadToday();if(name==="portfolio")loadPortfolio();if(name==="relationships")loadRelationships();scrollTo({top:0,behavior:"smooth"});}

function openCapture(){const d=$("captureDialog");$("captureStatus").textContent="";$("capturePreview").hidden=true;state.preview=null;d.showModal();setTimeout(()=>$("captureText").focus(),50);}
async function interpretCapture(){const text=$("captureText").value.trim();const button=$("interpretCapture");button.disabled=true;button.textContent="Interpretando…";$("captureStatus").className="status";try{const data=await api("/painel/api/os/captura/interpretar",{method:"POST",body:JSON.stringify({text})});state.preview=data;renderPreview(data);$("captureStatus").textContent="Confira os dados. Nada foi salvo ainda.";}catch(e){$("captureStatus").className="status error";$("captureStatus").textContent=e.message;}finally{button.disabled=false;button.textContent="Interpretar cadastro";}}
function renderPreview(data){const p=data.property||{},o=data.owner||{};const fields=[["Tipo",typeLabelProperty(p.propertyType)],["Bairro",p.neighborhood||"A confirmar"],["Quartos",p.bedrooms??"A confirmar"],["Preço",money(p.askingPrice)],["Proprietário",o.name||"A confirmar"],["Permuta",p.acceptsSwap?"Aceita":"Não informada"]];$("previewFields").replaceChildren(...fields.map(([l,v])=>el("div",{class:"preview-field"},[el("small",{text:l}),el("strong",{text:String(v)})])));$("previewMissing").replaceChildren(...(data.missing||[]).map(x=>el("li",{text:x})));$("capturePreview").hidden=false;}
const typeLabelProperty=t=>({apartamento:"Apartamento",casa:"Casa",terreno:"Terreno",galpao:"Galpão",sala_comercial:"Sala comercial",fazenda:"Fazenda",loja:"Loja"})[t]||"A confirmar";
async function confirmCapture(){if(!state.preview)return;const button=$("confirmCapture");button.disabled=true;button.textContent="Criando imóvel…";try{const data=await api("/painel/api/os/captura/confirmar",{method:"POST",body:JSON.stringify(state.preview)});$("captureDialog").close();$("captureText").value="";state.preview=null;state.loaded.today=false;state.loaded.portfolio=false;toast(`${data.property.title} criado. Próximos passos preparados.`);switchView("today");await loadToday(true);}catch(e){$("captureStatus").className="status error";$("captureStatus").textContent=e.message;}finally{button.disabled=false;button.textContent="Confirmar e criar imóvel";}}

document.querySelectorAll(".nav-item[data-target]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.target)));
$("openCapture").addEventListener("click",openCapture);$("interpretCapture").addEventListener("click",interpretCapture);$("confirmCapture").addEventListener("click",confirmCapture);$("refreshToday").addEventListener("click",()=>loadToday(true));
loadToday();
